VELZIA_ACHIEVEMENTS = {
    # Subscripcion
    'primer_pago': {
        'id': 'primer_pago',
        'name': 'Primer Pago',
        'description': 'Completa tu primer pago en Velzia.',
        'icon': 'credit_score',
        'category': 'suscripcion',
        'rarity': 'common',
        'secret': False,
        'reward_tokens': 5,
    },
    'tres_meses': {
        'id': 'tres_meses',
        'name': '3 Meses con Velzia',
        'description': 'Manten tu suscripcion activa por 3 meses.',
        'icon': 'calendar_month',
        'category': 'suscripcion',
        'rarity': 'uncommon',
        'secret': False,
        'reward_tokens': 15,
    },
    'seis_meses': {
        'id': 'seis_meses',
        'name': '6 Meses con Velzia',
        'description': 'Manten tu suscripcion activa por 6 meses.',
        'icon': 'calendar_month',
        'category': 'suscripcion',
        'rarity': 'rare',
        'secret': False,
        'reward_tokens': 30,
    },
    'un_ano': {
        'id': 'un_ano',
        'name': '1 Año con Velzia',
        'description': 'Un año entero con nosotros. ¡Eres familia!',
        'icon': 'calendar_today',
        'category': 'suscripcion',
        'rarity': 'legendary',
        'secret': False,
        'reward_tokens': 100,
    },

    # IA
    'primer_analisis': {
        'id': 'primer_analisis',
        'name': 'Mi primera conversación',
        'description': 'Tu primera conversación con IA.',
        'icon': 'psychology',
        'category': 'ia',
        'rarity': 'common',
        'secret': False,
        'reward_tokens': 5,
    },
    'diez_analisis': {
        'id': 'diez_analisis',
        'name': 'Mis 10 consejos',
        'description': 'Diez consejos que marcan la diferencia.',
        'icon': 'auto_awesome',
        'category': 'ia',
        'rarity': 'uncommon',
        'secret': False,
        'reward_tokens': 20,
    },
    'cincuenta_analisis': {
        'id': 'cincuenta_analisis',
        'name': '50 conversaciones con Copilot VZ',
        'description': 'Cincuenta charlas. Ya eres todo un experto.',
        'icon': 'bolt',
        'category': 'ia',
        'rarity': 'rare',
        'secret': False,
        'reward_tokens': 50,
    },
    'cien_analisis': {
        'id': 'cien_analisis',
        'name': 'Estratega en Ventas',
        'description': 'Cien conversaciones. Eres un estratega en ventas.',
        'icon': 'rocket_launch',
        'category': 'ia',
        'rarity': 'legendary',
        'secret': False,
        'reward_tokens': 100,
    },

    # Sorpresa Velzia
    'primer_sorpresa': {
        'id': 'primer_sorpresa',
        'name': 'Primera Sorpresa',
        'description': 'Reclama tu primera Sorpresa Velzia.',
        'icon': 'card_giftcard',
        'category': 'eventos',
        'rarity': 'common',
        'secret': False,
        'reward_tokens': 10,
    },
    'coleccionista_1': {
        'id': 'coleccionista_1',
        'name': 'Bronce',
        'description': 'Obtuviste una medalla de rareza Comun en Sorpresa Velzia.',
        'icon': 'toll',
        'category': 'eventos',
        'rarity': 'uncommon',
        'secret': False,
        'reward_tokens': 15,
    },
    'coleccionista_2': {
        'id': 'coleccionista_2',
        'name': 'Plata',
        'description': 'Obtuviste una medalla de rareza Poco Comun en Sorpresa Velzia.',
        'icon': 'toll',
        'category': 'eventos',
        'rarity': 'rare',
        'secret': False,
        'reward_tokens': 25,
    },
    'coleccionista_3': {
        'id': 'coleccionista_3',
        'name': 'Oro',
        'description': 'Obtuviste una medalla de rareza Muy Raro en Sorpresa Velzia.',
        'icon': 'workspace_premium',
        'category': 'eventos',
        'rarity': 'legendary',
        'secret': False,
        'reward_tokens': 50,
    },

    # Fidelidad
    'fundador_2026': {
        'id': 'fundador_2026',
        'name': 'Fundador Velzia 2026',
        'description': 'Solo los primeros 100 negocios. Nunca volvera.',
        'icon': 'military_tech',
        'category': 'fidelidad',
        'rarity': 'legendary',
        'secret': False,
        'reward_tokens': 100,
    },
    'madrugador': {
        'id': 'madrugador',
        'name': 'Madrugador',
        'description': 'Desbloquea 3 logros en tu primer mes.',
        'icon': 'wb_sunny',
        'category': 'fidelidad',
        'rarity': 'uncommon',
        'secret': False,
        'reward_tokens': 15,
    },

    # Especiales (Secretos)
    'tocador_sorpresa': {
        'id': 'tocador_sorpresa',
        'name': 'Tocador de Sorpresas',
        'description': 'Reclama 3 Sorpresas Velzia. Tsss... secreto.',
        'icon': 'masks',
        'category': 'especiales',
        'rarity': 'rare',
        'secret': True,
        'reward_tokens': 30,
    },
    'coleccionista_total': {
        'id': 'coleccionista_total',
        'name': 'Coleccionista Total',
        'description': 'Consigue las 3 rarezas de Sorpresa Velzia. Shhh...',
        'icon': 'diamond',
        'category': 'especiales',
        'rarity': 'legendary',
        'secret': True,
        'reward_tokens': 100,
    },
}

CATEGORIES = {
    'suscripcion': {'icon': 'credit_card', 'name': 'Suscripcion'},
    'ia': {'icon': 'psychology', 'name': 'IA'},
    'eventos': {'icon': 'card_giftcard', 'name': 'Eventos'},
    'fidelidad': {'icon': 'favorite', 'name': 'Fidelidad'},
    'especiales': {'icon': 'star', 'name': 'Especiales'},
}

RARITY_ORDER = {'common': 0, 'uncommon': 1, 'rare': 2, 'legendary': 3}
