"""create verduras catalog tables (categories, products, price_history)

Revision ID: 3fdc7c9baadf
Revises: 
Create Date: 2026-09-20 18:41:18.062321

"""
import sqlalchemy as sa
from alembic import op

import app.models.core

# revision identifiers, used by Alembic.
revision = '3fdc7c9baadf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """create verduras catalog tables"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verduras_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', app.models.core.AwareDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_verduras_categories_business_name')
    )
    op.create_table('verduras_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=10), server_default='kg', nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', app.models.core.AwareDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', app.models.core.AwareDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['verduras_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_verduras_products_business_name')
    )
    with op.batch_alter_table('verduras_products', schema=None) as batch_op:
        batch_op.create_index('ix_verduras_products_business', ['business_id'], unique=False)

    op.create_table('verduras_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', app.models.core.AwareDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.models.core.AwareDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['verduras_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verduras_price_history', schema=None) as batch_op:
        batch_op.create_index('ix_verduras_price_history_product', ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verduras_price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_verduras_price_history_product')

    op.drop_table('verduras_price_history')
    with op.batch_alter_table('verduras_products', schema=None) as batch_op:
        batch_op.drop_index('ix_verduras_products_business')

    op.drop_table('verduras_products')
    op.drop_table('verduras_categories')
    # ### end Alembic commands ###
