"""add pinned to copilot_conversation

Revision ID: 68f3dd225165
Revises: f61d4097ff5a
Create Date: 2026-07-14 10:17:31.756718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f3dd225165'
down_revision = 'f61d4097ff5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copilot_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copilot_conversations', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    op.create_table('velzia_budget',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('categoryId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['velzia_category.id'], name=op.f('Budget_categoryId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('velzia_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Budget_categoryId_month_year_key'), ['categoryId', 'month', 'year'], unique=True)

    op.create_table('velzia_category',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('velzia_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Category_name_userId_key'), ['name', 'userId'], unique=True)

    op.create_table('velzia_expense',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('amountConfidence', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('date', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('categoryId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('receiptUrl', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('ocrText', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('items', mysql.TEXT(), nullable=True),
    sa.Column('itemsConfidence', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['velzia_category.id'], name=op.f('Expense_categoryId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
