"""sync full model changes

Revision ID: e8f91dc009be
Revises: 697da4a0778f
Create Date: 2026-07-01 21:33:48.238859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8f91dc009be'
down_revision = '697da4a0778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('selected_plan', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_registrations_email'), ['email'], unique=True)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'date', name='uq_restaurant_date')
    )
    with op.batch_alter_table('velzia_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Budget_categoryId_month_year_key'))

    op.drop_table('velzia_budget')
    op.drop_table('velzia_expense')
    with op.batch_alter_table('velzia_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Category_name_userId_key'))

    op.drop_table('velzia_category')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_ip_address'), ['ip_address'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_highlighted')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ntfy_topic', sa.String(length=64), nullable=True))
        batch_op.alter_column('pending_expiry_hours',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint(None, ['ntfy_topic'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pending_expiry_hours',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('ntfy_topic')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_highlighted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ip_address'))
        batch_op.drop_column('ip_address')

    op.create_table('velzia_budget',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('categoryId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['velzia_category.id'], name=op.f('Budget_categoryId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('velzia_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Budget_categoryId_month_year_key'), ['categoryId', 'month', 'year'], unique=True)

    op.create_table('velzia_expense',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('amountConfidence', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('date', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('categoryId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('receiptUrl', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('ocrText', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('items', mysql.TEXT(), nullable=True),
    sa.Column('itemsConfidence', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['velzia_category.id'], name=op.f('Expense_categoryId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('velzia_category',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('velzia_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Category_name_userId_key'), ['name', 'userId'], unique=True)

    op.drop_table('order_counters')
    op.drop_table('expenses')
    with op.batch_alter_table('pre_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_registrations_email'))

    op.drop_table('pre_registrations')
    # ### end Alembic commands ###
